# https://catalog.redhat.com/en/software/containers/ubi9/nginx-120/61a609f2bfd4a5234d596287
FROM registry.access.redhat.com/ubi9/nginx-120:9.8

COPY ui/dist/ .
COPY images/sbomer-ui/run-with-env.sh /deployments/run-with-env.sh

USER root

RUN chown 1001:0 /opt/app-root/src/config.js && \
    chmod ug+rw /opt/app-root/src/config.js && \
    chmod 755 /deployments/run-with-env.sh

USER 1001

ENTRYPOINT ["/deployments/run-with-env.sh"]
