# https://catalog.redhat.com/software/containers/ubi9/nginx-120/61a609f2bfd4a5234d596287
FROM registry.access.redhat.com/ubi9/nginx-120@sha256:f4a47712867390a744119de36cdac8a4738977bb9473744a94a8c9302e597411

COPY ui/dist/ .
COPY images/sbomer-ui/run-with-env.sh /deployments/run-with-env.sh

USER root

RUN chown 1001:0 /opt/app-root/src/config.js && \
    chmod ug+rw /opt/app-root/src/config.js && \
    chmod 755 /deployments/run-with-env.sh

USER 1001

ENTRYPOINT ["/deployments/run-with-env.sh"]
