# https://catalog.redhat.com/software/containers/ubi9/nginx-120/61a609f2bfd4a5234d596287
FROM registry.access.redhat.com/ubi9/nginx-120@sha256:c5fdf1b976571cf1f058b8f2dd955a94d80ced7a43756362d7e87d99e9c92337

# Copy your custom Nginx config to the default location
COPY images/sbomer-ui/nginx.conf /etc/nginx/nginx.conf

# Copy your UI files.
COPY ui/dist/ .

# Copy the entrypoint script
COPY --chown=0755 images/sbomer-ui/run-with-env.sh /deployments/run-with-env.sh

USER root
# Set permissions:
# 1. Make the new Nginx config readable
# 2. Give user 1001 ownership of config.js (for the entrypoint)
# 3. Ensure entrypoint is executable
RUN chmod 644 /etc/nginx/nginx.conf && \
    chown 1001:0 /opt/app-root/src/config.js && \
    chmod 755 /deployments/run-with-env.sh

# Switch to the non-root user
USER 1001

# Run the script as USER 1001
ENTRYPOINT ["/deployments/run-with-env.sh"]
